datetime:
  i3:
    prefix: 
    format: 01/02/06 <b>15:04:05</b>
  tmux:
    format: 15:04:05

ram:
  i3:
    format: "%percentage%"
    unit: Go
    rounding: 2
  tmux:
    format: "%used% / %total% %unit% - %free%"
    unit: Go
    rounding: 2

ip:
  tmux:
    interface: ['enp37s0']
    no_ip: No address